import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { codecFromInit, fragmentStart, isInit, findBox } from './mp4.js';
import { fmtGap, rangeIndexAt, nextRangeStart } from './time.js';

// Generated by `go test ./internal/mux/ -run TestWriteFixture` in streamhub.
const FIXTURE = new URL('./testdata/segment.mp4', import.meta.url);

test('parses streamhub fMP4', { skip: !existsSync(FIXTURE) && 'fixture missing' }, () => {
  const u8 = new Uint8Array(readFileSync(FIXTURE));
  assert.ok(isInit(u8));
  assert.equal(codecFromInit(u8), 'avc1.64000a');
  const moov = findBox(u8, ['moov']);
  const frag = u8.subarray(moov[0] + moov[1]);
  assert.ok(!isInit(frag));
  assert.equal(fragmentStart(frag), 160_000_000_000_000);
});

test('fmtGap', () => {
  assert.equal(fmtGap(9 * 60_000), '09:00');
  assert.equal(fmtGap(5_400), '00:05');
  assert.equal(fmtGap(3600_000 + 5 * 60_000), '01:05:00');
});

test('range lookup', () => {
  const rs = [[0, 10], [20, 30], [40, 50]];
  assert.equal(rangeIndexAt(rs, 5), 0);
  assert.equal(rangeIndexAt(rs, 10), -1); // end is exclusive
  assert.equal(rangeIndexAt(rs, 20), 1);
  assert.equal(rangeIndexAt(rs, 35), -1);
  assert.equal(rangeIndexAt(rs, 60), -1);
  assert.equal(nextRangeStart(rs, 10), 20);
  assert.equal(nextRangeStart(rs, 45), null);
});

import { LabelStore, DecisionStore, topCat, parseSidecar, describeDecision } from './labels.js';

test('label store lookup', () => {
  const s = new LabelStore();
  for (const ms of [100, 300, 200]) s.add({ pts: ms * 90, dets: [{ score: ms }] });
  assert.equal(s.at(50), null);
  assert.equal(s.at(100).ms, 100);
  assert.equal(s.at(250).ms, 200);
  assert.equal(s.at(1000).ms, 300);
  s.add({ pts: 200 * 90, dets: [] }); // duplicate ignored
  assert.equal(s.items.length, 3);
});

test('topCat', () => {
  assert.equal(topCat({ cats: { a: 0.7, b: 0.3 } }), 'a');
  assert.equal(topCat({ cats: { a: 0.4, b: 0.35, c: 0.25 } }), 'unknown');
  assert.equal(topCat({}), 'cat');
});

test('parseSidecar splits results and decisions, skips partial lines', () => {
  const r = parseSidecar('{"t":"cv","pts":1,"dets":[]}\n{"t":"decision","pts":2}\n{"t":"other"}\n{"t":"cv","pt');
  assert.deepEqual(r.results, [{ t: 'cv', pts: 1, dets: [] }]);
  assert.deepEqual(r.decisions, [{ t: 'decision', pts: 2 }]);
});

test('decision store and description', () => {
  const s = new DecisionStore();
  s.add({ feeder: 'f2', pts: 90 * 100, state: 'closed', action: 'close', reason: 'no_cat' });
  s.add({ feeder: 'f1', pts: 90 * 200, state: 'open', action: 'open', reason: 'chuzh', identity: 'chuzh', conf: 0.97 });
  assert.deepEqual(s.at(150).map(d => d.feeder), ['f2']);
  const now = s.at(300);
  assert.equal(now.length, 2);
  assert.equal(describeDecision(now[0]), 'f1: open · chuzh 97%');
  assert.equal(describeDecision({ feeder: 'f3', state: 'closed', action: 'close', reason: 'not_allowed:alisa', identity: 'alisa', conf: 0.9, display: 'CA9N' }),
    'f3: closed · alisa 90% · not_allowed:alisa · [CA9N]');
});

import { select, encode, decode } from './selection.js';

test('camera selection', () => {
  const all = ['grey', 'beige', 'black'];
  assert.deepEqual(select(null, all, 'beige', false), ['beige']);
  assert.equal(select(['beige'], all, 'beige', false), null);          // click the only one: back to all
  assert.deepEqual(select(null, all, 'beige', true), ['grey', 'black']); // ctrl: hide one
  assert.deepEqual(select(['black'], all, 'grey', true), ['grey', 'black']); // ctrl: add, config order
  assert.equal(select(['grey', 'black'], all, 'beige', true), null);   // all again
  assert.deepEqual(select(['grey'], all, 'grey', true), ['grey']);     // never empty
  assert.equal(encode(null), 'all');
  assert.deepEqual(decode(encode(['grey', 'black']), all), ['grey', 'black']);
  assert.equal(decode('pink', all), null);
});
