"""Feeder door decision logic.

Pure function: maps (ZoneSummary, allowed_cats, dangerous_confusions) →
(action, reason). Nothing here is hardcoded — the allowed identities and the
dangerous-confusion policy are passed in from config (env, generated by
configure.py from cameras.yaml).

Decision rules (evaluated in order):
  not present                          → "close",  "no_cat"
  n_cats >= 2 (sustained simultaneous) → "close",  "multi_cat"
  identity is None                     → "close",  "no_identity"
  identity not in allowed_cats         → "close",  "not_allowed:<cat>"
  identity confidence < min_confidence → "close",  "low_confidence:<cat>"
  identity margin < min_margin         → "close",  "low_margin:<cat>"  (only when a
    top-2 margin is available; see ZoneSummary.margin TODO — never faked)
  identity blocked by a dangerous      → "close",  "dangerous_confusion:<actual>~<predicted>"
    confusion (block_open)
  identity in allowed_cats             → "open",   <cat>

Temporal stability is handled upstream: ZoneState aggregates a sliding window of
weighted votes (single weak frames can't win) and DoorFSM debounces the verdict
(an open must hold for open_debounce_sec). decide() stays a pure per-snapshot
function; the FSM is what turns a flickering verdict into "no open".
"""
from __future__ import annotations

import json
from dataclasses import dataclass

from zone_state import ZoneSummary


@dataclass(frozen=True)
class DangerousConfusion:
    """A configured identity confusion that is unsafe to act on.

    ``predicted`` is what the model might output while the cat is really
    ``actual``. ``action`` is the policy when that prediction would open a
    feeder (currently only ``block_open``)."""
    actual: str
    predicted: str
    action: str = "block_open"


def parse_dangerous_confusions(raw: str) -> list[DangerousConfusion]:
    """Parse a JSON list of {actual, predicted, action} from a config string.
    Empty/blank → []. Raises ValueError on malformed JSON/items so the caller
    can fail loudly or fall back."""
    raw = (raw or "").strip()
    if not raw:
        return []
    data = json.loads(raw)
    out: list[DangerousConfusion] = []
    for item in data:
        out.append(DangerousConfusion(
            actual=str(item["actual"]),
            predicted=str(item["predicted"]),
            action=str(item.get("action", "block_open")),
        ))
    return out


def decide(
    snap: ZoneSummary,
    allowed_cats: list[str],
    dangerous_confusions: "list[DangerousConfusion] | tuple" = (),
    *,
    min_confidence: float = 0.0,
    min_margin: float = 0.0,
) -> tuple[str | None, str]:
    if not snap.present:
        return "close", "no_cat"

    if snap.n_cats >= 2:
        return "close", "multi_cat"

    if snap.identity is None:
        return "close", "no_identity"

    cat = snap.identity

    if cat not in allowed_cats:
        return "close", f"not_allowed:{cat}"

    # Confidence gate (decision-level, configurable). Only applies when a real
    # classifier score is available for the winning identity.
    if (min_confidence > 0
            and snap.identity_score is not None
            and snap.identity_score < min_confidence):
        return "close", f"low_confidence:{cat}"

    # Margin gate. Only fires when a top1−top2 margin is actually available — the
    # event stream doesn't carry top-2 today, so this is inert until the detector
    # populates ZoneSummary.margin. We never synthesise a margin from votes.
    if (min_margin > 0
            and snap.margin is not None
            and snap.margin < min_margin):
        return "close", f"low_margin:{cat}"

    # Config-driven safety gate: if the resolved identity is a label that a
    # configured dangerous confusion says could really be a NON-allowed cat,
    # refuse to open — better to skip a meal than feed the wrong cat.
    for dc in dangerous_confusions:
        if (dc.action == "block_open"
                and dc.predicted == cat
                and dc.actual not in allowed_cats):
            return "close", f"dangerous_confusion:{dc.actual}~{cat}"

    return "open", cat
