"""Feeder door decision logic.

Pure function: maps (ZoneSummary, allowed_cats, dangerous_confusions) →
(action, reason). Nothing here is hardcoded — the allowed identities and the
dangerous-confusion policy are passed in from config (env, generated by
configure.py from cameras.yaml).

Decision rules (evaluated in order):
  not present                          → "close",  "no_cat"
  n_cats >= 2 (sustained simultaneous) → "close",  "multi_cat"
  identity is None                     → "close",  "no_identity"
  identity not in allowed_cats         → "close",  "not_allowed:<cat>"
  identity blocked by a dangerous      → "close",  "dangerous_confusion:<actual>~<predicted>"
    confusion (block_open)
  identity in allowed_cats             → "open",   <cat>
"""
from __future__ import annotations

import json
from dataclasses import dataclass

from zone_state import ZoneSummary


@dataclass(frozen=True)
class DangerousConfusion:
    """A configured identity confusion that is unsafe to act on.

    ``predicted`` is what the model might output while the cat is really
    ``actual``. ``action`` is the policy when that prediction would open a
    feeder (currently only ``block_open``)."""
    actual: str
    predicted: str
    action: str = "block_open"


def parse_dangerous_confusions(raw: str) -> list[DangerousConfusion]:
    """Parse a JSON list of {actual, predicted, action} from a config string.
    Empty/blank → []. Raises ValueError on malformed JSON/items so the caller
    can fail loudly or fall back."""
    raw = (raw or "").strip()
    if not raw:
        return []
    data = json.loads(raw)
    out: list[DangerousConfusion] = []
    for item in data:
        out.append(DangerousConfusion(
            actual=str(item["actual"]),
            predicted=str(item["predicted"]),
            action=str(item.get("action", "block_open")),
        ))
    return out


def decide(
    snap: ZoneSummary,
    allowed_cats: list[str],
    dangerous_confusions: "list[DangerousConfusion] | tuple" = (),
) -> tuple[str | None, str]:
    if not snap.present:
        return "close", "no_cat"

    if snap.n_cats >= 2:
        return "close", "multi_cat"

    if snap.identity is None:
        return "close", "no_identity"

    cat = snap.identity

    if cat not in allowed_cats:
        return "close", f"not_allowed:{cat}"

    # Config-driven safety gate: if the resolved identity is a label that a
    # configured dangerous confusion says could really be a NON-allowed cat,
    # refuse to open — better to skip a meal than feed the wrong cat.
    for dc in dangerous_confusions:
        if (dc.action == "block_open"
                and dc.predicted == cat
                and dc.actual not in allowed_cats):
            return "close", f"dangerous_confusion:{dc.actual}~{cat}"

    return "open", cat
