import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Dev-time proxy table. Mirrors the prod nginx config (which is generated by
// tools/configure.py). One pair of rules per camera (detector + detector-control),
// plus the shared mediamtx (WHEP + recordings) and the static /cameras.json.
//
// Host resolution: in the dev container we reach mediamtx via host.docker.internal
// (it has network_mode: host). Per-camera detectors are on the bridge network,
// reachable by container name (detector-<id>).
const mediamtxHost = process.env.MEDIAMTX_HOST || 'host.docker.internal';

function loadCameras() {
  try {
    const j = JSON.parse(readFileSync(resolve('./public/cameras.json'), 'utf-8'));
    return (j && j.cameras) || [];
  } catch (e) {
    console.warn('[vite] no public/cameras.json — run `just configure` from live2/. Proxy table will be empty.');
    return [];
  }
}

function buildProxy() {
  const cameras = loadCameras();
  const proxy = {
    '/whep': {
      target: `http://${mediamtxHost}:8889`, changeOrigin: true,
      rewrite: p => p.replace(/^\/whep/, ''),
    },
    '/recordings': {
      target: `http://${mediamtxHost}:9996`, changeOrigin: true,
      rewrite: p => p.replace(/^\/recordings/, ''),
    },
  };
  for (const cam of cameras) {
    proxy[`/detector/${cam.id}`] = {
      target: `http://detector-${cam.id}:8091`, ws: true, changeOrigin: true,
      rewrite: p => p.replace(new RegExp(`^/detector/${cam.id}`), ''),
    };
    proxy[`/detector-control/${cam.id}`] = {
      target: `http://detector-${cam.id}:8092`, changeOrigin: true,
      rewrite: p => p.replace(new RegExp(`^/detector-control/${cam.id}`), ''),
    };
  }
  return proxy;
}

export default defineConfig({
  plugins: [svelte()],
  build: { outDir: 'dist', emptyOutDir: true },
  server: {
    host: '0.0.0.0',
    port: 5173,
    strictPort: true,
    watch: { usePolling: true, interval: 300 },
    proxy: buildProxy(),
  },
});
