"""Render the multi-camera config files from cameras.yaml.

Generates (all marked with `# GENERATED ...` headers):
  - mediamtx/mediamtx.yml             one path per camera + global server config
  - docker-compose.cameras.yml        one `detector-<id>` service per camera
  - docker-compose.cameras.dev.yml    watchfiles override per detector (for `just dev`)
  - webui/nginx.conf                  per-camera detector upstreams + routing
  - webui/public/cameras.json         camera list the UI fetches at startup

Run via `just configure` (or `python tools/configure.py`) from the live2/
directory after editing cameras.yaml. Generated files ARE committed so the
codebase is self-contained and diffs are inspectable; rerun whenever
cameras.yaml changes.

Networking model (important if you're chasing connectivity issues):
- mediamtx stays on the HOST network (network_mode: host) — needed so
  WebRTC ICE candidates resolve from the browser.
- Each detector runs on the DEFAULT bridge network with extra_hosts
  mapping host.docker.internal → host-gateway, so the detector reaches
  mediamtx at host.docker.internal:8554.
- webui (also on the bridge network) reaches each detector by container
  name on the docker DNS (detector-<id>). The webui's nginx fans out
  /detector/<id>/* and /detector-control/<id>/* to the right upstream.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
CAMERAS_YAML = ROOT / "cameras.yaml"

ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def load_config() -> dict:
    if not CAMERAS_YAML.exists():
        sys.exit(f"missing {CAMERAS_YAML} — copy cameras.yaml.example and edit")
    cfg = yaml.safe_load(CAMERAS_YAML.read_text())
    if not isinstance(cfg, dict) or "cameras" not in cfg:
        sys.exit("cameras.yaml must define a top-level `cameras:` list")
    if not cfg["cameras"]:
        sys.exit("cameras.yaml: at least one camera is required")
    seen_cam = set()
    seen_feeder = set()
    for cam in cfg["cameras"]:
        cid = cam.get("id")
        if not cid or not ID_RE.match(cid):
            sys.exit(f"invalid or missing camera id {cid!r} (must match {ID_RE.pattern})")
        if cid in seen_cam:
            sys.exit(f"duplicate camera id: {cid}")
        # mediamtx env-override path keys use '_' as the separator, so it
        # derives the key for MTX_PATHS_<KEY>_SOURCE by splitting on '_'. A
        # hyphenated path name can't be addressed this way (it would create a
        # mismatched key), and the RTSP source is now passed exclusively via
        # that env var — so camera ids feeding mediamtx must be hyphen-free.
        if "-" in cid:
            sys.exit(
                f"camera id {cid!r} must not contain '-': it becomes a mediamtx "
                "path overridden via MTX_PATHS_<ID>_SOURCE, whose key cannot "
                "carry hyphens"
            )
        seen_cam.add(cid)
        if not cam.get("rtsp"):
            sys.exit(f"camera {cid}: missing rtsp")
        feeder = cam.get("feeder")
        if feeder is not None:
            fid = feeder.get("id")
            if not fid or not ID_RE.match(fid):
                sys.exit(
                    f"camera {cid}: feeder.id {fid!r} invalid (must match {ID_RE.pattern})"
                )
            if fid in seen_feeder:
                sys.exit(f"camera {cid}: duplicate feeder id: {fid}")
            seen_feeder.add(fid)
            if not feeder.get("api_base_url"):
                sys.exit(f"camera {cid}: feeder.api_base_url is required")
            if not feeder.get("serial_number"):
                sys.exit(f"camera {cid}: feeder.serial_number is required")
            allowed = feeder.get("allowed_cats", [])
            if not isinstance(allowed, list) or not allowed:
                sys.exit(f"camera {cid}: feeder.allowed_cats must be a non-empty list")
    return cfg


# ---- mediamtx ----------------------------------------------------------------

def mtx_source_env(cid: str) -> str:
    """Env var mediamtx reads to source path <cid> (see render_mediamtx)."""
    return f"MTX_PATHS_{cid.upper()}_SOURCE"


def render_mediamtx(cfg: dict) -> str:
    out = [
        "# GENERATED by tools/configure.py from cameras.yaml — do not edit by hand.",
        "logLevel: info",
        "logDestinations: [stdout]",
        "",
        "webrtc: yes",
        "webrtcAddress: :8889",
        "webrtcAllowOrigins: ['*']",
        "webrtcEncryption: no",
        f"webrtcAdditionalHosts: [{cfg.get('webrtc_host', '127.0.0.1')!r}]",
        "",
        "hls: yes",
        "hlsAddress: :8888",
        "hlsAllowOrigins: ['*']",
        "hlsVariant: fmp4",
        "hlsSegmentDuration: 1s",
        "",
        "rtsp: yes",
        "rtspAddress: :8554",
        "rtspTransports: [tcp]",
        "",
        "rtmp: no",
        "srt: no",
        "",
        "api: yes",
        "apiAddress: :9997",
        "playback: yes",
        "playbackAddress: :9996",
        "",
        "paths:",
    ]
    for cam in cfg["cameras"]:
        out += [
            f"  {cam['id']}:",
            # The RTSP source carries camera credentials and must NOT be written
            # to this committed file. mediamtx does no ${VAR} substitution in
            # YAML, so the source is injected at runtime via the env var below
            # (set from the gitignored secrets/cameras.env via docker-compose).
            f"    # source: set via {mtx_source_env(cam['id'])} (secrets/cameras.env)",
            "    sourceProtocol: tcp",
            "    sourceOnDemand: no",
            "    record: yes",
            "    recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f",
            "    recordFormat: fmp4",
            "    recordSegmentDuration: 30s",
            "    recordPartDuration: 1s",
            "    recordDeleteAfter: 720h",
        ]
    return "\n".join(out) + "\n"


# ---- docker-compose ----------------------------------------------------------

def render_compose(cfg: dict) -> str:
    services = []

    for cam in cfg["cameras"]:
        cid = cam["id"]
        env = {
            "CAMERA_ID":           cid,
            "RTSP_SOURCE":         f"rtsp://host.docker.internal:8554/{cid}",
            "DETECTOR_TYPE":       cam.get("detector_type", "blob"),
            "BLOB_BRIGHT_THRESHOLD": cam.get("blob_bright_threshold", 240),
            "BLOB_MIN_AREA":       cam.get("blob_min_area", 500),
            "YOLO_WEIGHTS":        cam.get("yolo_weights", "/opt/models/yolov8n_int8_openvino_model/"),
            "YOLO_CONF":           cam.get("yolo_conf", 0.25),
            "CLASSIFIER_WEIGHTS":  cam.get("classifier_weights", "/opt/models/cat_classifier_openvino/"),
            "CLASSIFIER_MIN_CONF": cam.get("classifier_min_conf", 0.5),
            "CLASSIFIER_PAD_FRAC": cam.get("classifier_pad_frac", 0.15),
            "DETECT_ROI":          cam.get("detect_roi", "0,0,1,1"),
            "ACTION_POLYGON":      cam.get("action_polygon", "0,0,1,1"),
            "FRAME_ROTATE_DEG":    cam.get("rotate_deg", 0),
            "EVENTS_DB":           "/data/events/events.db",
            "WS_PORT":             "8091",
            "CONTROL_PORT":        "8092",
            "ARTIFICIAL_DELAY_MS": cam.get("artificial_delay_ms", 0),
        }
        env_lines = "\n".join(f"      {k}: {json.dumps(v)}" for k, v in env.items())
        services.append(f"""\
  detector-{cid}:
    build: ./detector
    container_name: detector-{cid}
    restart: unless-stopped
    depends_on: [mediamtx]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
{env_lines}
    volumes:
      - ./data/events:/data/events
""")

        # Optional feeder service — generated only if feeder block present.
        feeder = cam.get("feeder")
        if feeder:
            fid = feeder["id"]
            allowed_cats = ",".join(feeder.get("allowed_cats", []))
            cooldown_json = json.dumps(feeder.get("cooldown_hours", {}))
            feeder_env = {
                "CAMERA_ID":               cid,
                "FEEDER_ID":               fid,
                "FEEDER_API_BASE_URL":     feeder["api_base_url"],
                "FEEDER_SERIAL_NUMBER":    feeder["serial_number"],
                "ALLOWED_CATS":            allowed_cats,
                "COOLDOWN":                cooldown_json,
                "DOOR_CLOSE_TIMEOUT_SEC":  str(feeder.get("door_close_timeout_sec", 30)),
                "MIN_MEAL_SEC":            str(feeder.get("min_meal_sec", 10)),
                "PRESENCE_WINDOW_SEC":     str(feeder.get("presence_window_sec", 5)),
                "CLASSIFIER_MIN_CONF":     str(feeder.get("classifier_min_conf", 0.9)),
                "OPEN_DEBOUNCE_SEC":       str(feeder.get("open_debounce_sec", 3)),
                "MULTI_DEBOUNCE_SEC":      str(feeder.get("multi_debounce_sec", 2)),
            }
            feeder_env_lines = "\n".join(
                f"      {k}: {json.dumps(v)}" for k, v in feeder_env.items()
            )
            services.append(f"""\
  feeder-{fid}:
    build: ./feeder
    container_name: feeder-{fid}
    restart: unless-stopped
    depends_on: [detector-{cid}]
    environment:
{feeder_env_lines}
    volumes:
      - ./data/cooldowns:/data/cooldowns
""")

    return (
        "# GENERATED by tools/configure.py from cameras.yaml — do not edit.\n"
        "services:\n" + "\n".join(services)
    )


def render_compose_dev(cfg: dict) -> str:
    services = []
    for cam in cfg["cameras"]:
        cid = cam["id"]
        services.append(f"""\
  detector-{cid}:
    volumes:
      - ./detector:/app
      - ./data/events:/data/events
    command: ["python", "-u", "-m", "watchfiles", "--filter", "python", "python -u main.py", "/app"]
""")
    return (
        "# GENERATED by tools/configure.py from cameras.yaml — do not edit.\n"
        "services:\n" + "\n".join(services)
    )


# ---- nginx -------------------------------------------------------------------

def render_nginx(cfg: dict) -> str:
    # Hyphens aren't allowed in nginx upstream names; map id → safe name.
    def safe(cid: str) -> str:
        return cid.replace("-", "_")

    upstreams = "\n".join(
        f"upstream detector_{safe(cam['id'])}      {{ server detector-{cam['id']}:8091; }}\n"
        f"upstream detector_{safe(cam['id'])}_ctl  {{ server detector-{cam['id']}:8092; }}"
        for cam in cfg["cameras"]
    )
    detector_locations = "\n\n".join(f"""\
    location /detector/{cam['id']}/ {{
        proxy_pass http://detector_{safe(cam['id'])}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }}
    location /detector-control/{cam['id']}/ {{
        proxy_pass http://detector_{safe(cam['id'])}_ctl/;
        proxy_http_version 1.1;
    }}""" for cam in cfg["cameras"])
    return f"""# GENERATED by tools/configure.py from cameras.yaml — do not edit.
{upstreams}

server {{
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {{
        try_files $uri /index.html;
        add_header Cache-Control "no-store" always;
    }}

    # Per-camera detector REST + WS + control endpoints.
{detector_locations}

    # mediamtx (single instance, multiple paths) — path is part of the query string.
    location /whep/ {{
        proxy_pass http://host.docker.internal:8889/;
        proxy_http_version 1.1;
    }}
    location /recordings/ {{
        proxy_pass http://host.docker.internal:9996/;
        proxy_http_version 1.1;
        add_header Access-Control-Allow-Origin "*" always;
    }}
}}
"""


# ---- secrets (gitignored) ----------------------------------------------------

def render_secrets_env(cfg: dict) -> str:
    """Per-camera RTSP source (with credentials) as env vars for mediamtx.

    Written to secrets/cameras.env (gitignored) and loaded into the mediamtx
    container via docker-compose `env_file`. This is the ONLY place the RTSP
    credentials live on disk in the repo tree, and it never gets committed."""
    lines = [
        "# GENERATED by tools/configure.py from cameras.yaml — DO NOT COMMIT.",
        "# Contains camera RTSP credentials; loaded into the mediamtx container.",
    ]
    for cam in cfg["cameras"]:
        lines.append(f"{mtx_source_env(cam['id'])}={cam['rtsp']}")
    return "\n".join(lines) + "\n"


# ---- cameras.json (UI consumes) ---------------------------------------------

def render_cameras_json(cfg: dict) -> str:
    cams = [
        {
            "id":    cam["id"],
            "label": cam.get("label", cam["id"].replace("-", " ").title()),
        }
        for cam in cfg["cameras"]
    ]
    return json.dumps({"cameras": cams}, indent=2) + "\n"


# ---- main --------------------------------------------------------------------

def main():
    cfg = load_config()
    targets = {
        ROOT / "mediamtx" / "mediamtx.yml":           render_mediamtx(cfg),
        ROOT / "docker-compose.cameras.yml":          render_compose(cfg),
        ROOT / "docker-compose.cameras.dev.yml":      render_compose_dev(cfg),
        ROOT / "webui" / "nginx.conf":                render_nginx(cfg),
        ROOT / "webui" / "public" / "cameras.json":   render_cameras_json(cfg),
    }
    for path, body in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
        print(f"wrote {path.relative_to(ROOT)}")

    # Secrets are written separately: gitignored, never part of `targets` (which
    # are all committed). chmod 600 so credentials aren't world-readable.
    secrets_path = ROOT / "secrets" / "cameras.env"
    secrets_path.parent.mkdir(parents=True, exist_ok=True)
    secrets_path.write_text(render_secrets_env(cfg))
    secrets_path.chmod(0o600)
    print(f"wrote {secrets_path.relative_to(ROOT)} (gitignored — camera credentials)")


if __name__ == "__main__":
    main()
